Ols = {
    SYSTEM_USERID: '__LOOPY__',
    SYSTEM_USERNAME: 'loopy',

    MESSAGE_TYPE_CHAT:'MESSAGE_TYPE_CHAT',
    MESSAGE_TYPE_CUSTOM:'MESSAGE_TYPE_CUSTOM',
    MESSAGE_TYPE_SYSTEM:'MESSAGE_TYPE_SYSTEM',

    PROJECT_TYPE_STANDARD: 'PROJECT_TYPE_STANDARD',
    PROJECT_TYPE_CONVERSATION_DEFAULT: 'PROJECT_TYPE_CONVERSATION_DEFAULT',

    ROLE_USER: 'ROLE_USER',
    ROLE_ADMIN: 'ROLE_ADMIN',

    DEFAULT_PAGE_SIZE: 50
};