Ols = {
    SYSTEM_USERID: '__LOOPY__',
    SYSTEM_USERNAME: 'loopy',

    LOOPBOT_USERID: 'loopbot',
    LOOPBOT_USERNAME: 'loopbot',

    MESSAGE_TYPE_CHAT:'MESSAGE_TYPE_CHAT',
    MESSAGE_TYPE_CUSTOM:'MESSAGE_TYPE_CUSTOM',
    MESSAGE_TYPE_SYSTEM:'MESSAGE_TYPE_SYSTEM',
    MESSAGE_TYPE_ACTIVITY:'MESSAGE_TYPE_ACTIVITY',
    MESSAGE_TYPE_LOOPBOT: 'MESSAGE_TYPE_LOOPBOT',

    MESSAGE_SUBTYPE_LOOPBOT_PROMPT: 'MESSAGE_SUBTYPE_LOOPBOT_PROMPT',
    MESSAGE_SUBTYPE_LOOPBOT_INFO: 'MESSAGE_SUBTYPE_LOOPBOT_INFO',
    MESSAGE_SUBTYPE_LOOPBOT_ERROR: 'MESSAGE_SUBTYPE_LOOPBOT_ERROR',

    PROJECT_TYPE_STANDARD: 'PROJECT_TYPE_STANDARD',

    DEFAULT_PAGE_SIZE: 150
};